---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: forwarder-vpp
spec:
  template:
    spec:
      containers:
      - name: forwarder-vpp
        # image: daniluzlov/daniluzlov-test:fwd-1.8-2
        resources:
          limits:
            cpu: null
      #   volumeMounts:
      #   - name: vpp-conf
      #     mountPath: /etc/vpp/helper
      # volumes:
      # - name: vpp-conf
      #   configMap:
      #     name: fwd-vpp-conf
