---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-k8s
spec:
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      containers:
      - name: registry
        resources:
          limits:
            cpu: null
