---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      annotations:
        networkservicemesh.io: kernel://my-vl3-network/nsm-1?dnsName=nginx
      labels:
        app: nginx
    spec:
      volumes:
      - name: config
        configMap:
          name: nginx-kuma-config
      containers:
      - name: nginx
        image: nginx:1.23.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
