---
apiVersion: v1
kind: Service
metadata:
  name: kuma-ingress
  namespace: kuma-system
spec:
  type: NodePort
  ports:
    - port: 10001
      protocol: TCP
      targetPort: 10001
      nodePort: 30091
