---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-ingress
  namespace: kuma-system
spec:
  template:
    spec:
      containers:
      - name: ingress
        resources:
          limits:
            cpu: null
